package es.uniovi.eii.ds.main;

import java.io.*;
import java.util.Scanner;

import es.uniovi.eii.ds.editor.core.Editor;

public class Main {
    
    private Scanner in;
    private PrintStream out;

    public static void main(String[] args) {
        new Main().run();
    }

    // Simulates the user interaction with the editor. Note that it does not 
    // represent the user interface itself (not even a text-based one), but the
    // system events that would be generated by the graphical library in a real 
    // application. Therefore, it is not part of the editor's logic, and should 
    // remain in this main class as is.
    //
    private void run() {
        Editor editor = new Editor();

        in = new Scanner(System.in);
        out = System.out;

        showHelp();
        do {
            String userInput = askUser();
            
            // Split the user input into thee action and its arguments (if any).
            // For example:
            // "click 100, 200" -> [ "click", "100, 200" ]
            // "draw"           -> [ "draw" ]
            String[] parts = userInput.split(" ", 2);
            
            String action = parts[0];

            if (action.equals("exit")) {
                break;
            }  else if (action.equals("help")) {
                showHelp();
            } else if (action.equals("draw")) {
                editor.draw();
            } else if (action.equals("selection") || action.equals("rectangle") ||
                       action.equals("circle")    || action.equals("triangle")) {
                editor.toolButtonPressed(action);
            } else if (action.equals("click")) {
                Point p = parseCoordinates(userInput);
                editor.mousePressed(p.x, p.y);
            } else if (action.equals("move")) {
                Point p = parseCoordinates(userInput);
                editor.mouseMoved(p.x, p.y);
            } else if (action.equals("release")) {
                Point p = parseCoordinates(userInput);
                editor.mouseReleased(p.x, p.y);
            } else {
                out.println("Unknown action");
            }
        } while (true);
        out.println("Bye!");
    }

    private boolean isMouseAction(String action) {
        return action.equals("click") || action.equals("move") || action.equals("release");
    }

    // Asks the user for input and performs some basic input validation. Specifically, if the
    // number or format of the arguments is not correct for that action, it shows an error message
    // and continues asking the user until a valid input is provided.
    //
    private String askUser() {
        while (true) {
            out.print("% ");
            out.flush();

            String userInput = in.nextLine().trim();

            if (userInput.isEmpty())
                continue;
            
            String[] parts = userInput.split(" ", 2);
            String action = parts[0];

            if (isMouseAction(action)) {
                if (parseCoordinates(userInput) == null)
                    continue;
            } else {
                // The rest of actions do not take coordinates
                if (parts.length > 1) {
                    out.println("Error: '" + action + "' does not expect arguments");
                    continue;
                }
            }
           
            return userInput;
        }
    }
    
    private void showHelp() {
		out.println("");
		out.println("Tools: selection - rectangle - circle - triangle");
		out.println("Mouse actions: click <x>,<y> - move <x>,<y> - release <x>,<y>");
		out.println("Other options: draw - help - exit");
		out.println("-------------------------------------------------------------");
    }

	// Receives a string with the user input, with the mouse event and the coordinates.
    // If the format is not the expected one ("<event> <x>, <y>"), it shows an error
    // message and returns null.
	//
    // For example:
    //
    //   "click 100, 200" -> Point(100, 200)
    //   "move 100, abc"  -> null (and shows an error message)
    //   "released 100"   -> null (and shows an error message)
    //
	private Point parseCoordinates(String userInput) {
        try {
            String[] parts = userInput.split(" ", 2);
            String[] arguments = parts[1].split("\\s*,\\s*");
            int x = Integer.parseInt(arguments[0]);
            int y = Integer.parseInt(arguments[1]);
            return new Point(x, y);
        } catch (Exception e) {
            out.println("Error: expected coordinates in the format: x, y");
            return null;
        }
	}

	private record Point(int x, int y) {}
}
